

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
     name: Default

    steps:
    - task: PowerShell@2
       inputs:
       targetType: 'inline'
        script: |
          $pythonInstallerUrl = 'https://www.python.org/ftp/python/3.9.0/python-3.9.0-amd64.exe'
          $pythonInstallerPath = "$env:TEMP\python-3.9.0-amd64.exe"
          Invoke-WebRequest -Uri $pythonInstallerUrl -OutFile $pythonInstallerPath
  

    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
