

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
     name: Default
    steps:
    - task: PowerShell@2
      inputs:
       targetType: 'inline'
       script: |
            steps:
              - task: UsePythonVersion@0
                inputs:
                  versionSpec: '$(python.version)'
                   displayName: 'Use Python $(python.version)'
                

                   script: 'pip install pytest pytest-azurepipelines ; pytest unit_test/'

    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
