apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobportal-container-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobportal
  template:
    metadata:
      name: jobportal-pod
      labels:
        app: jobportal
    spec:
      containers:
        - name: jobportal-container
          image: sumitchavan0110/jobportalimage:latest
          command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
          ports:
<<<<<<< HEAD
            - containerPort: 8000
=======
            - containerPort: 8000
>>>>>>> 3fb074e1bf99acdcee83d05c2ce5caa971092c13
