apiVersion: v1
kind: Service
metadata:
  name: JobPortal-container-app-deployment
spec:
  type: NodePort
  selector:
    app: JobPortal
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30018
